spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.17.100
    port: 6379
server:
  port: 12000

logging:
  level:
    com.ctz.gulimail: debug
