spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.17.100
    port: 6379
  session:
    store-type: redis
server:
  port: 20000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


